feat: cambios en mensaje de test de Makefile

diff --git a/pa4-virtual-memory-sim/Makefile b/pa4-virtual-memory-sim/Makefile
--- a/pa4-virtual-memory-sim/Makefile
+++ b/pa4-virtual-memory-sim/Makefile
@@ -8,11 +8,14 @@ memory_management: $(OBJS)
 memory_management.o: memory_management.c
 
 test: memory_management
-	./memory_management data/addresses.txt correct_out.txt
-	@if diff correct_out.txt test/correct.txt > /dev/null; then \
+	./memory_management data/addresses.txt output.txt
+	@diff_lines=$$(diff output.txt test/correct.txt | grep -c '^[<>]') ; \
+	if [ $$diff_lines -eq 0 ]; then \
 		echo "EXITO -> ARCHIVOS IDÉNTICOS"; \
+		exit 0; \
 	else \
-		echo "ERROR -> ARCHIVOS DISTINTOS"; \
+		echo "ERROR -> ARCHIVOS DISTINTOS: $$diff_lines líneas diferentes"; \
+		exit 1; \
 	fi
 
 clean:
